//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventBillApplication.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventDBEntities : DbContext
    {
        public EventDBEntities()
            : base("name=EventDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserMaster> UserMasters { get; set; }
        public DbSet<UserTypeMaster> UserTypeMasters { get; set; }
        public DbSet<EventMaster> EventMasters { get; set; }
        public DbSet<EventCustomer> EventCustomers { get; set; }
        public DbSet<EventEntryMaster> EventEntryMasters { get; set; }
        public DbSet<BillSettlementmaster> BillSettlementmasters { get; set; }
        public DbSet<CreditAmountDetail> CreditAmountDetails { get; set; }
    }
}
