//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventBillApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTypeMaster
    {
        public UserTypeMaster()
        {
            this.UserMasters = new HashSet<UserMaster>();
        }
    
        public int Id { get; set; }
        public string Usertype { get; set; }
    
        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}
